# Generated by Django 3.2.12 on 2022-03-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
