# Generated by Django 3.2.12 on 2022-04-18 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_alter_gift_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='group',
            new_name='groups',
        ),
    ]
