# Generated by Django 3.2.12 on 2022-05-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='invited_to',
            field=models.ManyToManyField(related_name='invitations', to='members.Club'),
        ),
    ]
