# Generated by Django 3.2.12 on 2022-03-15 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member',
            new_name='name',
        ),
    ]
