# Generated by Django 3.2.12 on 2022-05-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_invited_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='match',
            field=models.JSONField(null=True),
        ),
    ]
