# Generated by Django 3.2.12 on 2022-03-15 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_member_member_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
